### ISSUE TITLE
Double Jumping Mechanic - Time: 2 hours 

### ISSUE THREAD

**Issue by Courtney-jade1997** [UoSGamesGroups/second-semester-s2-level-4-5-group-10#11]
**Double Jumping:**
As a programmer you will add double jumping into our game so that the players can reach high and low places without difficulty. While play testing we saw that when the player jumped they couldn't reach the higher surfaces , once this is added we will play test again to see if it has made it easier.

**Comment by AKegge** [comment]
The player can now jump twice before landing again.
