### ISSUE TITLE
Falling Object Spawner- Time: 3 hours 

### ISSUE THREAD

**Issue by Courtney-jade1997** [UoSGamesGroups/second-semester-s2-level-4-5-group-10#12]
**Falling Object Spawner:**
As a programmer, you will create a falling object spawn at the top of our game level so the items will fall in certain patterns. 
For example;
Once both players have started their match , we want the random items ( explosive chickens + health) to fall from the sky in certain areas. Once the explosives have hit the surface where the players are continuing their match , we want the explosives to explode, pushing the players back and destroying the blocks underneath where the explosive interacted with the surface.

**Comment by AKegge** [comment]
Logged time: 3 hours.
Objects now fall from random places at top of the screen every (random time between 5 and 20 seconds, this time can be easily changed) at a random angle, they destroy blocks they collide with and disappear when they hit something.
