### ISSUE TITLE
Friction - Add friction on the platform. Time: 3hrs

### ISSUE THREAD

**Issue by Courtney-jade1997** [UoSGamesGroups/second-semester-s2-level-4-5-group-10#2]
**Friction** needs to be added to the platform to act as ice on the rink. Remember that the player is playing as a drunk character, think about the way the character will move. 
- slow movement. 
- slippery ice will make the character move forward and backwards. 
- If an object hits the platform how will it move?

**Comment by AKegge** [comment]
Players colliding and getting stuck on contiguous corners of blocks might be avoided by giving them a circle collider with rotation locked.
