### ISSUE TITLE
Push Back Mechanic - Time: 3 hours

### ISSUE THREAD

**Issue by Courtney-jade1997** [UoSGamesGroups/second-semester-s2-level-4-5-group-10#26]
**Push Back Mechanic**
As a programmer you will create a push-back mechanic for when the falling objects collides with the player. When the falling object falls from the top of the screen it will collide with the player, if it touches the player it will explode and continue to destroy the block where it falls.

**Comment by AKegge** [comment]
Players are now pushed back when they collide with a falling object.
