### ISSUE TITLE
Create beer falling mechanic - Time: 1 hour 30 min

### ISSUE THREAD

**Issue by Courtney-jade1997** [UoSGamesGroups/second-semester-s2-level-4-5-group-10#34]
**Create Beer Falling Mechanic** 
As a programmer you will create a beer falling mechanic. Once the beer has fallen it will regenerate the players health.

**Comment by AKegge** [comment]
'beer' will now fall 1 in 4 times instead of a chicken and increases health by the same amount as spikes and falling off the screen decreases health.
